const { chromium } = require('playwright');
const fs = require('fs');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const results=[]; const errors=[];
  const check=(name,ok,detail)=>results.push([name,Boolean(ok),detail]);
  async function run(viewport,label){
    const page=await browser.newPage({viewport});
    page.on('pageerror',e=>errors.push(`${label}: ${e.message}`));
    await page.goto('http://127.0.0.1:8899/index.html?v=unique-model-qa',{waitUntil:'networkidle'});
    await page.locator('#models').scrollIntoViewIfNeeded();
    const all=await page.locator('.model-card').count();
    check(`${label}: 24 unique model cards`,all===24,all);
    const state=await page.evaluate(()=>({names:models.map(m=>m.name),configs:models.reduce((n,m)=>n+m.configurationCount,0),unique:new Set(models.map(m=>m.name)).size,claude:models.filter(m=>m.name==='Claude Opus 5').length}));
    check(`${label}: 40 benchmark configurations preserved`,state.configs===40,state.configs);
    check(`${label}: card names are unique`,state.unique===24,state.unique);
    check(`${label}: Claude Opus 5 appears once`,state.claude===1,state.claude);
    for(const name of ['Kimi K2.6','Qwen3.7 Plus','Gemini 3.5 Flash-Lite']) check(`${label}: ${name} present`,state.names.includes(name));
    await page.locator('.proof-filter[data-proof="quarantine"]').click();
    check(`${label}: needs-more-proof filter returns 3`,await page.locator('.model-card').count()===3,await page.locator('.model-card').count());
    await page.locator('.proof-filter[data-proof="all"]').click();
    await page.locator('#modelSort').selectOption('speed');
    check(`${label}: speed sort puts Flash-Lite first`,(await page.locator('.model-card h3').first().innerText())==='Gemini 3.5 Flash-Lite',await page.locator('.model-card h3').first().innerText());
    await page.locator('#modelSearchInput').fill('Claude Opus 5 (Adaptive Reasoning, Xhigh Effort)');
    check(`${label}: variant search maps to one card`,await page.locator('.model-card').count()===1,await page.locator('.model-card').count());
    check(`${label}: variant search maps to Claude Opus 5`,(await page.locator('.model-card h3').innerText())==='Claude Opus 5',await page.locator('.model-card h3').innerText());
    await page.locator('.model-detail-btn').click();
    check(`${label}: Claude evidence guide opens`,await page.locator('#evidenceModal').isVisible());
    check(`${label}: Claude guide maps 5 configurations`,await page.locator('#evConfigBody tr').count()===5,await page.locator('#evConfigBody tr').count());
    const settings=await page.locator('#evConfigBody tr td:first-child').allInnerTexts();
    check(`${label}: Xhigh setting retained`,settings.includes('Adaptive Reasoning, Xhigh Effort'),settings);
    await page.keyboard.press('Escape');
    await page.locator('#modelSearchInput').fill('Kimi K2.6');
    await page.locator('.model-detail-btn').click();
    check(`${label}: provider proof link`,(await page.locator('#evSourceLink').getAttribute('href'))==='https://platform.kimi.ai/docs/guide/kimi-k2-6-quickstart',await page.locator('#evSourceLink').getAttribute('href'));
    check(`${label}: pricing proof link`,(await page.locator('#evPricingLink').getAttribute('href'))==='https://platform.kimi.ai/docs/pricing/chat-k26',await page.locator('#evPricingLink').getAttribute('href'));
    await page.keyboard.press('Escape');
    check(`${label}: Escape closes guide`,!(await page.locator('#evidenceModal').isVisible()));
    const overflow=await page.evaluate(()=>{const sec=document.getElementById('models');const sr=sec.getBoundingClientRect();return [...sec.querySelectorAll('*')].some(el=>{const r=el.getBoundingClientRect();return r.width>0&&(r.left<sr.left-1||r.right>sr.right+1)})});
    check(`${label}: Section 7 has no horizontal overflow`,!overflow,{sectionWidth:await page.evaluate(()=>document.getElementById('models').getBoundingClientRect().width),viewport:await page.evaluate(()=>document.documentElement.clientWidth)});
    if(label==='mobile') await page.screenshot({path:'/Users/satyyy/Documents/R&D - C3ALABS/LLM-Intelligence-Repository/qa/section7-mobile-390x844.png',fullPage:false});
    await page.close();
  }
  await run({width:1440,height:1000},'desktop');
  await run({width:390,height:844},'mobile');
  await browser.close();
  const pass=results.filter(x=>x[1]).length; const out={pass,total:results.length,errors,results};
  fs.writeFileSync('/Users/satyyy/Documents/R&D - C3ALABS/LLM-Intelligence-Repository/qa/section7_cards_validation.json',JSON.stringify(out,null,2));
  console.log(JSON.stringify(out,null,2));
  process.exit(pass===results.length&&errors.length===0?0:1);
})().catch(e=>{console.error(e);process.exit(1)});
